fleet:
  - robot_name: otto600
    robot_namespace: otto_1
    lane: Line1
    tasks_config_file: config/otto600_tasks_12.yaml
    nav2_param_file: otto600Params.yaml
    position: 
      x: -30.0
      y: 2.0
      z: 0.1

  - robot_name: otto600
    robot_namespace: otto_2
    lane: Line1
    tasks_config_file: config/otto600_tasks_12.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -28.0
      y: 2.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_3
    lane: Line2
    tasks_config_file: config/otto600_tasks_12.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -26.0
      y: 2.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_4
    lane: Line2
    tasks_config_file: config/otto600_tasks_12.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -24.0
      y: 2.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_5
    lane: Line3
    tasks_config_file: config/otto600_tasks_34.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -30.0
      y: 27.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_6
    lane: Line3
    tasks_config_file: config/otto600_tasks_34.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -28.0
      y: 27.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_7
    lane: Line4
    tasks_config_file: config/otto600_tasks_34.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -26.0
      y: 27.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_8
    lane: Line4
    tasks_config_file: config/otto600_tasks_34.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -24.0
      y: 27.0
      z: 0.2

########################

  - robot_name: otto600
    robot_namespace: otto_21
    lane: Line21
    tasks_config_file: config/otto600_tasks_12_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position: 
      x: -30.0
      y: 32.0
      z: 0.1

  - robot_name: otto600
    robot_namespace: otto_22
    lane: Line21
    tasks_config_file: config/otto600_tasks_12_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -28.0
      y: 32.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_23
    lane: Line22
    tasks_config_file: config/otto600_tasks_12_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -26.0
      y: 32.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_24
    lane: Line22
    tasks_config_file: config/otto600_tasks_12_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -24.0
      y: 32.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_25
    lane: Line23
    tasks_config_file: config/otto600_tasks_34_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -30.0
      y: 57.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_26
    lane: Line23
    tasks_config_file: config/otto600_tasks_34_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -28.0
      y: 57.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_27
    lane: Line24
    tasks_config_file: config/otto600_tasks_34_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -26.0
      y: 57.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_28
    lane: Line24
    tasks_config_file: config/otto600_tasks_34_lane2.yaml
    nav2_param_file: otto600Params.yaml
    position:
      x: -24.0
      y: 57.0
      z: 0.2


  # - robot_name: otto1500
  #   robot_namespace: otto_5
  #   lane: OTTO1500
  #   tasks_config_file: config/otto1500_tasks.yaml
  #   nav2_param_file: otto1500Params.yaml
  #   position: 
  #     x: -36.0
  #     y: 11.0
  #     z: 0.1

arms:
  - namespace: ur1
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur2
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur3
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur4
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur5
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur6
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur7
    num_of_boxes: 6
    launch_rviz: false

  - namespace: ur8
    num_of_boxes: 6
    launch_rviz: false

    