fleet:
  - robot_name: otto
    robot_namespace: otto_1
    position: 
      x: -4.0
      y: 3.2
      z: 0.2

  - robot_name: otto
    robot_namespace: otto_2
    position: 
      x: -13.0
      y: 0.5
      z: 0.2

  # - robot_name: otto
  #   robot_namespace: otto_3
  #   position: 
  #     x: 1.0
  #     y: -2.5
  #     z: 0.2